package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import Game.Item;
import Game.Player;
import food.Fruit;
import medicine.EpiPen;
import medicine.PetMedicine;
import pets.Cat;
import pets.Pets;

public class PetMedicineTest {
	
	@Rule
	public ExpectedException thrown = ExpectedException.none();
	
	/**
	 * Test if I can break a PetMedicine. Since it is a consumable, should expect it to fail and throw an exception
	 * if there are still uses.
	 */
	@Test
	public void testBreakPetMedicine() {
		Item testPetMedicine = new PetMedicine();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testPetMedicine);
		thrown.expect(RuntimeException.class);
		thrown.expectMessage("Can't remove/break a consumable when still has uses.");
		testPetMedicine.breakItem(itemOwner);
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are PetMedicines.
	 */
	@Test
	public void testEquals() {
		Item petMedicine1 = new PetMedicine();
		Item petMedicine2 = new PetMedicine();
		Item notPetMedicine = new Fruit();
		
		assertTrue(petMedicine1.equals(petMedicine2));
		assertFalse(petMedicine1.equals(notPetMedicine));
	}
	
	/**
	 * Test the hash code generated by the PetMedicine item.
	 */
	@Test
	public void testHashCode() {
		Item petMedicine = new PetMedicine();
		double restoreValue = petMedicine.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, petMedicine.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a PetMedicine instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testPetMedicine = new PetMedicine();
		testPetMedicine.increaseNumUses();
		assertEquals(2, testPetMedicine.getNumUses());
		testPetMedicine.increaseNumUses(2);
		assertEquals(4, testPetMedicine.getNumUses());
	}

	/**
	 * Test if a single consumable medicine item added to the player's inventory will be
	 * removed after its use. Inventory should be empty afterwards.
	 */
	@Test
	public void testUsePetMedicine() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new PetMedicine());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test if multiple medicine instances (that are stacked in the player's inventory) 
	 * will be removed after use.
	 */
	@Test
	public void testUseStackedPetMedicine() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new PetMedicine());
		testPlayer.addItem(new PetMedicine());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(2, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(1, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test it correctly identifies a PetMedicine instance to be a medical item.
	 */
	@Test
	public void testIsMedicine() {
		Item testPetMed = new PetMedicine();
		assertTrue(testPetMed.isMedicine());
		assertFalse(testPetMed.isFood());
		assertFalse(testPetMed.isToy());
	}
}
