package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Test;

import Game.Item;
import Game.Player;
import medicine.PetMedicine;
import pets.Pets;
import toy.Pool;

public class PoolTest {

	
	/**
	 * Test if I can break a pool. Since it is a non-consumable toy, should expect it to be removed
	 * from the user's inventory when it breaks. 
	 */
	@Test
	public void testBreakPool() {
		Item testPool = new Pool();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testPool);
		assertEquals(1, itemOwner.getInventory().size());
		testPool.breakItem(itemOwner);
		assertEquals(0, itemOwner.getInventory().size());
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are pools.
	 */
	@Test
	public void testEquals() {
		Item pool1 = new Pool();
		Item pool2 = new Pool();
		Item notPool = new PetMedicine();
		
		assertTrue(pool1.equals(pool2));
		assertFalse(pool1.equals(notPool));
	}
	
	/**
	 * Test the hash code generated by the pool item.
	 */
	@Test
	public void testHashCode() {
		Item pool = new Pool();
		double restoreValue = pool.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, pool.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a pool instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testPool = new Pool();
		int poolUses = testPool.getNumUses();
		testPool.increaseNumUses();
		assertEquals(poolUses + 1, testPool.getNumUses());
		testPool.increaseNumUses(2);
		assertEquals(poolUses + 3, testPool.getNumUses());
	}

	/**
	 * Test if a single non-consumable pool item added to the player's inventory will be
	 * in the player's inventory until the durability/uses drops to 0.
	 */
	@Test
	public void testUsePool() {
		class SuperPet extends Pets {
			/**
			 * Pet that never gets tired (for testing only).
			 */

			public SuperPet(String givenName) {
				super(givenName);
				super.energy = Double.MAX_VALUE;
			}
			
			@Override
			public String eat(Item f) {
				//too nothing
				return null;
			}

			@Override
			public String sleep() {
				//Do nothing
				return null;
			}

			@Override
			public String playWithToy(Item t) {
				//Do nothing
				return null;
			}

			@Override
			public String heal(Item m) {
				//Do nothing
				return null;
			}
		}
		
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new SuperPet("Test Pet"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Pool());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		
		int poolUses = new Pool().getNumUses();

		//Use it until it gets to it's durability is reduced to 1
		for(int i = poolUses-1; i > 0; i--) {
			testPlayer.getInventory().get(0).use(testPlayer, testPet);
			assertEquals(i, testPlayer.getInventory().get(0).getNumUses());
		}
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		assertEquals(0, testPlayer.getInventory().size());

		
	}

}
