package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import Game.Item;
import Game.Player;
import food.Rat;
import food.Steak;
import medicine.PetMedicine;
import pets.Cat;
import pets.Pets;

public class RatTest {

	@Rule
	public ExpectedException thrown = ExpectedException.none();
	
	/**
	 * Test if I can break a rat. Since it is a consumable, should expect it to fail and throw an exception
	 * if there are still uses.
	 */
	@Test
	public void testBreakRat() {
		Item testRat = new Rat();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testRat);
		thrown.expect(RuntimeException.class);
		thrown.expectMessage("Can't remove/break a consumable when still has uses.");
		testRat.breakItem(itemOwner);
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are seeds.
	 */
	@Test
	public void testEquals() {
		Item rat1 = new Rat();
		Item rat2 = new Rat();
		Item notRat = new PetMedicine();
		
		assertTrue(rat1.equals(rat2));
		assertFalse(rat1.equals(notRat));
	}
	
	/**
	 * Test the hash code generated by the rat item.
	 */
	@Test
	public void testHashCode() {
		Item rat = new Rat();
		double restoreValue = rat.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, rat.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a rat instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testRat = new Rat();
		testRat.increaseNumUses();
		assertEquals(2, testRat.getNumUses());
		testRat.increaseNumUses(2);
		assertEquals(4, testRat.getNumUses());
	}

	/**
	 * Test if a single consumable food item added to the player's inventory will be
	 * removed after its use. Inventory should be empty afterwards.
	 */
	@Test
	public void testUseRat() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Rat());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test if multiple food instances (that are stacked in the player's inventory) 
	 * will be removed after use.
	 */
	@Test
	public void testUseStackedRat() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Rat());
		testPlayer.addItem(new Rat());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(2, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(1, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test it correctly identifies a rat instance to be a food item.
	 */
	@Test
	public void testIsFood() {
		Item testFood = new Rat();
		assertFalse(testFood.isMedicine());
		assertTrue(testFood.isFood());
		assertFalse(testFood.isToy());
	}

}
