package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Test;

import Game.Item;
import Game.Player;
import medicine.PetMedicine;
import pets.Pets;
import toy.Bone;
import toy.Slide;

public class SlideTest {

	/**
	 * Test if I can break a slide. Since it is a non-consumable toy, should expect it to be removed
	 * from the user's inventory when it breaks. 
	 */
	@Test
	public void testBreakSlide() {
		Item testSlide = new Slide();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testSlide);
		assertEquals(1, itemOwner.getInventory().size());
		testSlide.breakItem(itemOwner);
		assertEquals(0, itemOwner.getInventory().size());
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are slides.
	 */
	@Test
	public void testEquals() {
		Item slide1 = new Slide();
		Item slide2 = new Slide();
		Item notSlide = new PetMedicine();
		
		assertTrue(slide1.equals(slide2));
		assertFalse(slide1.equals(notSlide));
	}
	
	/**
	 * Test the hash code generated by the slide item.
	 */
	@Test
	public void testHashCode() {
		Item slide = new Slide();
		double restoreValue = slide.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, slide.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a slide instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testSlide = new Slide();
		int slideUses = testSlide.getNumUses();
		testSlide.increaseNumUses();
		assertEquals(slideUses + 1, testSlide.getNumUses());
		testSlide.increaseNumUses(2);
		assertEquals(slideUses + 3, testSlide.getNumUses());
	}

	/**
	 * Test if a single non-consumable slide item added to the player's inventory will be
	 * in the player's inventory until the durability/uses drops to 0.
	 */
	@Test
	public void testUseSlide() {
		class SuperPet extends Pets {
			/**
			 * Pet that never gets tired (for testing only).
			 */

			public SuperPet(String givenName) {
				super(givenName);
				super.energy = Double.MAX_VALUE;
			}
			
			@Override
			public String eat(Item f) {
				//too nothing
				return null;
			}

			@Override
			public String sleep() {
				//Do nothing
				return null;
			}

			@Override
			public String playWithToy(Item t) {
				//Do nothing
				return null;
			}

			@Override
			public String heal(Item m) {
				//Do nothing
				return null;
			}
		}
		
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new SuperPet("Test Pet"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Slide());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		
		int slideUses = new Slide().getNumUses();

		//Use it until it gets to it's durability is reduced to 1
		for(int i = slideUses-1; i > 0; i--) {
			testPlayer.getInventory().get(0).use(testPlayer, testPet);
			assertEquals(i, testPlayer.getInventory().get(0).getNumUses());
		}
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		assertEquals(0, testPlayer.getInventory().size());

		
	}

	/**
	 * Test it correctly identifies a slide instance to be a toy item.
	 */
	@Test
	public void testIsToy() {
		Item testToy = new Slide();
		assertFalse(testToy.isMedicine());
		assertFalse(testToy.isFood());
		assertTrue(testToy.isToy());
	}
}
