package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import Game.Item;
import Game.Player;
import food.Steak;
import medicine.PetMedicine;
import pets.Cat;
import pets.Pets;
import toy.Bone;

public class SteakTest {

	@Rule
	public ExpectedException thrown = ExpectedException.none();
	
	/**
	 * Test if I can break a steak. Since it is a consumable, should expect it to fail and throw an exception
	 * if there are still uses.
	 */
	@Test
	public void testBreakSteak() {
		Item testSteak = new Steak();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testSteak);
		thrown.expect(RuntimeException.class);
		thrown.expectMessage("Can't remove/break a consumable when still has uses.");
		testSteak.breakItem(itemOwner);
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are steaks.
	 */
	@Test
	public void testEquals() {
		Item steak1 = new Steak();
		Item steak2 = new Steak();
		Item notSteak = new PetMedicine();
		
		assertTrue(steak1.equals(steak2));
		assertFalse(steak1.equals(notSteak));
	}
	
	/**
	 * Test the hash code generated by the steak item.
	 */
	@Test
	public void testHashCode() {
		Item steak = new Steak();
		double restoreValue = steak.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, steak.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a steak instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testSteak = new Steak();
		testSteak.increaseNumUses();
		assertEquals(2, testSteak.getNumUses());
		testSteak.increaseNumUses(2);
		assertEquals(4, testSteak.getNumUses());
	}

	/**
	 * Test if a single consumable food item added to the player's inventory will be
	 * removed after its use. Inventory should be empty afterwards.
	 */
	@Test
	public void testUseSteak() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Steak());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test if multiple food instances (that are stacked in the player's inventory) 
	 * will be removed after use.
	 */
	@Test
	public void testUseStackedSteak() {
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new Cat("Test Cat"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Steak());
		testPlayer.addItem(new Steak());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(2, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(1, testPlayer.getInventory().size());
		assertEquals(1, testPlayer.getInventory().get(0).getNumUses());
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		
		assertEquals(0, testPlayer.getInventory().size());
	}
	
	/**
	 * Test it correctly identifies a steak instance to be a food item.
	 */
	@Test
	public void testIsFood() {
		Item testFood = new Steak();
		assertFalse(testFood.isMedicine());
		assertTrue(testFood.isFood());
		assertFalse(testFood.isToy());
	}

}
