package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Test;

import Game.Item;
import Game.Player;
import medicine.PetMedicine;
import pets.Pets;
import toy.Tube;

public class TubeTest {

	/**
	 * Test if I can break a tube. Since it is a non-consumable toy, should expect it to be removed
	 * from the user's inventory when it breaks. 
	 */
	@Test
	public void testBreakTube() {
		Item testTube = new Tube();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testTube);
		assertEquals(1, itemOwner.getInventory().size());
		testTube.breakItem(itemOwner);
		assertEquals(0, itemOwner.getInventory().size());
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are tubes.
	 */
	@Test
	public void testEquals() {
		Item tube1 = new Tube();
		Item tube2 = new Tube();
		Item notTube = new PetMedicine();
		
		assertTrue(tube1.equals(tube2));
		assertFalse(tube1.equals(notTube));
	}
	
	/**
	 * Test the hash code generated by the tube item.
	 */
	@Test
	public void testHashCode() {
		Item tube = new Tube();
		double restoreValue = tube.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, tube.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a tube instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testTube = new Tube();
		int tubeUses = testTube.getNumUses();
		testTube.increaseNumUses();
		assertEquals(tubeUses + 1, testTube.getNumUses());
		testTube.increaseNumUses(2);
		assertEquals(tubeUses + 3, testTube.getNumUses());
	}

	/**
	 * Test if a single non-consumable tube item added to the player's inventory will be
	 * in the player's inventory until the durability/uses drops to 0.
	 */
	@Test
	public void testUseTube() {
		class SuperPet extends Pets {
			/**
			 * Pet that never gets tired (for testing only).
			 */

			public SuperPet(String givenName) {
				super(givenName);
				super.energy = Double.MAX_VALUE;
			}
			
			@Override
			public String eat(Item f) {
				//too nothing
				return null;
			}

			@Override
			public String sleep() {
				//Do nothing
				return null;
			}

			@Override
			public String playWithToy(Item t) {
				//Do nothing
				return null;
			}

			@Override
			public String heal(Item m) {
				//Do nothing
				return null;
			}
		}
		
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new SuperPet("Test Pet"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new Tube());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		
		int tubeUses = new Tube().getNumUses();

		//Use it until it gets to it's durability is reduced to 1
		for(int i = tubeUses-1; i > 0; i--) {
			testPlayer.getInventory().get(0).use(testPlayer, testPet);
			assertEquals(i, testPlayer.getInventory().get(0).getNumUses());
		}
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		assertEquals(0, testPlayer.getInventory().size());

		
	}

}
