package JUnitTests;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Test;

import Game.Item;
import Game.Player;
import medicine.PetMedicine;
import pets.Pets;
import toy.Bone;
import toy.WoolBall;

public class WoolBallTest {

	/**
	 * Test if I can break a ball of wool. Since it is a non-consumable toy, should expect it to be removed
	 * from the user's inventory when it breaks. 
	 */
	@Test
	public void testBreakWoolBall() {
		Item testWoolBall = new WoolBall();
		Player itemOwner = new Player(new ArrayList<Pets>(), "Test Player");
		itemOwner.addItem(testWoolBall);
		assertEquals(1, itemOwner.getInventory().size());
		testWoolBall.breakItem(itemOwner);
		assertEquals(0, itemOwner.getInventory().size());
		
		
	}
	
	
	/**
	 * Test if we can accurately check if two different instances are balls of wool.
	 */
	@Test
	public void testEquals() {
		Item woolBall1 = new WoolBall();
		Item woolBall2 = new WoolBall();
		Item notWoolBall = new PetMedicine();
		
		assertTrue(woolBall1.equals(woolBall2));
		assertFalse(woolBall1.equals(notWoolBall));
	}
	
	/**
	 * Test the hash code generated by the woolBall item.
	 */
	@Test
	public void testHashCode() {
		Item woolBall = new WoolBall();
		double restoreValue = woolBall.getRestoreValue();
		int hashCode = (int) restoreValue * 31 + 17;
		assertEquals(hashCode, woolBall.hashCode());
	}
	
	/**
	 * Test if we can increase the number of uses of a ball of wool instance. 
	 */
	@Test
	public void testIncreaseNumUses() {
		Item testWoolBall = new WoolBall();
		int woolBallUses = testWoolBall.getNumUses();
		testWoolBall.increaseNumUses();
		assertEquals(woolBallUses + 1, testWoolBall.getNumUses());
		testWoolBall.increaseNumUses(2);
		assertEquals(woolBallUses + 3, testWoolBall.getNumUses());
	}

	/**
	 * Test if a single non-consumable woolBall item added to the player's inventory will be
	 * in the player's inventory until the durability/uses drops to 0.
	 */
	@Test
	public void testUseWoolBall() {
		class SuperPet extends Pets {
			/**
			 * Pet that never gets tired (for testing only).
			 */

			public SuperPet(String givenName) {
				super(givenName);
				super.energy = Double.MAX_VALUE;
			}
			
			@Override
			public String eat(Item f) {
				//too nothing
				return null;
			}

			@Override
			public String sleep() {
				//Do nothing
				return null;
			}

			@Override
			public String playWithToy(Item t) {
				//Do nothing
				return null;
			}

			@Override
			public String heal(Item m) {
				//Do nothing
				return null;
			}
		}
		
		ArrayList<Pets> pets = new ArrayList<Pets>();
		pets.add(new SuperPet("Test Pet"));
		Player testPlayer = new Player(pets, "Test Player");
		testPlayer.addItem(new WoolBall());
		
		Pets testPet = testPlayer.getPetArray().get(0);
		
		assertEquals(1, testPlayer.getInventory().size());
		
		int woolBallUses = new WoolBall().getNumUses();

		//Use it until it gets to it's durability is reduced to 1
		for(int i = woolBallUses-1; i > 0; i--) {
			testPlayer.getInventory().get(0).use(testPlayer, testPet);
			assertEquals(i, testPlayer.getInventory().get(0).getNumUses());
		}
		
		testPlayer.getInventory().get(0).use(testPlayer, testPet);
		assertEquals(0, testPlayer.getInventory().size());

		
	}
	
	/**
	 * Test it correctly identifies a ball of wool instance to be a toy item.
	 */
	@Test
	public void testIsToy() {
		Item testToy = new WoolBall();
		assertFalse(testToy.isMedicine());
		assertFalse(testToy.isFood());
		assertTrue(testToy.isToy());
	}

}
